name: Run Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code  
      uses: actions/checkout@v3

    - name: Use Python ${{ matrix.python_version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
        cache: "pip"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests-mock

    - name: Run Tests
      run: pytest  
